### ISSUE TITLE
Сделать форк проекта под организацией oscript-library

### ISSUE THREAD

**Issue by thedemoncat** [oscript-library/gitsync-plugins#11]
Если Gitsync 3.0.будет выпущен как стабильный, то этот репозитарий тоже должен быть в общей организации
@khorevaa @EvilBeaver @allustin  - призываю!

**Comment by khorevaa** [comment]
сделано!

**Comment by thedemoncat** [comment]
Для истории: https://github.com/oscript-library/gitsync-plugins
