### ISSUE TITLE
Не отображается список плагинов

### ISSUE THREAD

**Issue by ivtroitskiy** [oscript-library/gitsync-plugins#22]
tiv1c@SRVAUTOTEST1C M:\
# gitsync plugins init
ИНФОРМАЦИЯ - Начата инициализация предустановленных плагинов
ИНФОРМАЦИЯ - Устанавливаю пакет gitsync-plugins
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: <strings> из каталога локальных зависимостей
ИНФОРМАЦИЯ - <strings> уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Инициализация предустановленных плагинов завершена

tiv1c@SRVAUTOTEST1C M:\
# gitsync plugins list
Каталог плагинов: <C:\Users\tiv1c\AppData\Local\gitsync\plugins>
Список плагинов:

**Comment by khorevaa** [comment]
gitsync plugins list -a

**Comment by ivtroitskiy** [comment]
Заработало и с -a и без, не знаю что это было

**Comment by ivtroitskiy** [comment]
закрыто

**Comment by khorevaa** [comment]
`gitsync plugins list -a` - вывод все плагины включая выключенные
`gitsync plugins list`  - вывод только включенных плагинов
