### ISSUE TITLE
ошибка при работе v8unpack

### ISSUE THREAD

**Issue by ivvoronov** [oscript-library/gitsync-plugins#34]
ПРЕДУПРЕЖДЕНИЕ - Попытка удаления C:\Users\User\AppData\Local\Temp\tsxmue02.mr2.tmp закончилась неудачей, по причине {Модуль C:\Program Files (x86)\OneScript\lib\gitsync\oscript_modules\tempfiles\ВременныеФайлы.os / Ошибка в строке: 118 / Внешнее исключение (System.IO.IOException): The process cannot access the file 'Form.bin' because it is being used by another process.}
13:18:53 КРИТИЧНАЯОШИБКА - {Модуль C:\Users\IVoronov\AppData\Local\gitsync\plugins\gitsync-plugins\src\Классы\internal\v8unpack\Классы\РаспаковкаФорм.os / Ошибка в строке: 46 / Внешнее исключение (System.Reflection.TargetInvocationException): Exception has been thrown by the target of an invocation.}

Версия гитсинк - 3.1.0
Версия плагинов - 1.1.0
Версия oscript - 1.2.0.92

Отключить unpack не могу, он необходим.

**Comment by yukon39** [comment]
Аналогичная ошибка. Только oscript x64.

**Comment by khorevaa** [comment]
Ошибка связана не с плагинами а  с компонентой v8unpack.dll ее уже раз фиксили но не дофиксили!

**Comment by ivvoronov** [comment]
> Ошибка связана не с плагинами а с компонентой v8unpack.dll ее уже раз фиксили но не дофиксили!

Куда написать, чтобы исправили ошибку?

**Comment by khorevaa** [comment]
@ivvoronov   Исправлено в версии 1.1.1
