### ISSUE TITLE
При использовании плагина edtExport не работает инкрементальная выгрузка

### ISSUE THREAD

**Issue by yukon39** [oscript-library/gitsync-plugins#44]
При использовании плагина `edtExport` не работает плагин `increment`, т.к. в рабочей области не сохраняется служебный файл платформы `ConfigDumpInfo.xml`

Версия плагина: 1.2.0
Версия gitsync: 3.2.0

**Comment by yukon39** [comment]
~Просто добавить сохранение файла `ConfigDumpInfo.xml` в проекте не поможет - нужно полностью сохранять состояние платформенной выгрузки между запусками.~

**Comment by yukon39** [comment]
Так подразобрался, с помощью @marmyshev. Одним `ConfigDumpInfo.xml` не отделаться - надо, чтобы плагин инкремента дополнял список объектов к выгрузке "обязательными" объектами, например, Языками.

Если добавить это функционал к плагину инкремента, то на больших проектах можно значительно ускорить этап конвертации. В ГК это реализовано в функции [`КонвертацияХранилища.ПолучитьСписокОбъектовДовыгрузки`](https://github.com/1C-Company/GitConverter/blob/master/GitConverter/src/CommonModules/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B0%D1%86%D0%B8%D1%8F%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0/Module.bsl#L3092)

@khorevaa @sfaqer что скажете?

**Comment by khorevaa** [comment]
Я не возражаю! Жду ПР )

**Comment by sfaqer** [comment]
@yukon39 тут надо определить ответственность, все таки это нектороый "стык" между инкрементом и едт экспортом.
Вероятно если там все сильно замудренно то надо всю функциональность в edt export выносить, правда если нужно хранить состояния прошлой выгрузки, то это ещё и выгрузку конфигуратора надо в реп пихать, что не айс, можно подумать в сторону инкреиентов в рамках одной операции sync, типа каждый новый запуск как с чистого листа, но если грузим 500 версий скопом то инкременткльно. Что скажешь?

**Comment by yukon39** [comment]
@sfaqer Похоже не надо - `edt import` уже может работать с частичной выгрузкой. Надо только дополнить список объектов для платформенной выгрузки. Между сессиями сохранять кроме самого проекта ничего не нужно.

В папке проекта останется `ConfigDumpInfo.xml` - коммитить его в репу или нет уже другой вопрос.

В общем виде так:
1. Полная выгрузка - как сейчас
2. Инкрементная:
2.1. дополняем список объектов к выгрузке (increment)
2.2. выгружаем (increment)
2.3. конвертируем (edtExport)
2.4. копируем результат конвертации в папку проекта (поверх уже существующих файлов) (edtExport/increment ?)

Я собственно споткнулся на п. 2.3 - вываливалась ошибка, т.к. не был выполнен п. 2.1.

У меня основной режим запуска "по одному коммиту", т.к. хранилища уже сконвертированы, и сейчас в них добавляются новые коммиты по текущим изменениям.

**Comment by yukon39** [comment]
@khorevaa @sfaqer Изменения в PR.
