### ISSUE TITLE
Добавить в документацию описание переменных окружения GITSYNC_PLUGINS_PATH GITSYNC_PLUGINS_DIR GITSYNC_PL_DIR

### ISSUE THREAD

**Issue by pimchest** [oscript-library/gitsync-plugins#48]
![image](https://user-images.githubusercontent.com/32355274/101812411-5e340780-3b2c-11eb-9c03-7a8e265717c8.png)

**Comment by pimchest** [comment]
Переменные окружения определяют где gitsync ищет каталог с плагинами.

**Comment by khorevaa** [comment]
Надо перенести запрос в gitsync
