### ISSUE TITLE
Падает opm run testing-build

### ISSUE THREAD

**Issue by pravets** [oscript-library/gitsync-plugins#58]
develop ветка, выполняю сборку для тестирования.

Результат выполнения:
λ opm run testing-build
ИНФОРМАЦИЯ - Каталог сборки <E:\git\gitsync-plugins\tasks\..>
ИНФОРМАЦИЯ - Сборка пакета библиотеки
ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - Начинаю сборку в каталоге E:\git\gitsync-plugins\tasks\..
ИНФОРМАЦИЯ - Использую файл манифеста packagedef
ИНФОРМАЦИЯ - Загружаю описание пакета...
ИНФОРМАЦИЯ - Описание пакета прочитано
ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - ПРЕДУПРЕЖДЕНИЕ - При локальной установке параметр -dest игнорируется
ИНФОРМАЦИЯ - Устанавливаю зависимость: strings
ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - Скачиваю файл: strings-0.4.1.ospx
ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - Устанавливаю пакет strings
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - Записаны метаданные пакета
ИНФОРМАЦИЯ - Формирую определения модулей пакета (lib.config)
ИНФОРМАЦИЯ - Записаны определения модулей пакета
ИНФОРМАЦИЯ - Добавляем файл: src
ИНФОРМАЦИЯ - Добавляем файл: docs
ИНФОРМАЦИЯ - Добавляем файл: oscript_modules
ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - Создана сборка E:\git\gitsync-plugins\gitsync-plugins-1.4.0.ospx
ИНФОРМАЦИЯ - Сборка пакета завершена
ИНФОРМАЦИЯ - Установка пакета из файла <E:\git\gitsync-plugins\gitsync-plugins-1.4.0.ospx>
**ИНФОРМАЦИЯ - {Модуль E:\git\gitsync-plugins\bin\gitsync\oscript_modules\configor\src\Классы\internal\Классы\ПровайдерПараметровJSON.os / Ошибка в строке: 167,1 / Ожидается завершение директивы препроцессора #Область}**
{Модуль E:\git\gitsync-plugins\tasks\testing-build.os / Ошибка в строке: 74 / Ошибка установки плагинов из <E:\git\gitsync-plugins\gitsync-plugins-1.4.0.ospx> по причине <>}

Причина в устаревшей версии пакета configor. opm run gitsync-install ставит версию 0.6.3. Актуальная версия 0.7.0. В актуальной версии данной ошибки нет.

После исправления этой ошибки получаю следующую:

λ opm run testing-build
ИНФОРМАЦИЯ - Каталог сборки <E:\git\gitsync-plugins\tasks\..>
ИНФОРМАЦИЯ - Сборка пакета библиотеки
ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - Начинаю сборку в каталоге E:\git\gitsync-plugins\tasks\..
ИНФОРМАЦИЯ - Использую файл манифеста packagedef
ИНФОРМАЦИЯ - Загружаю описание пакета...
ИНФОРМАЦИЯ - Описание пакета прочитано
ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - ПРЕДУПРЕЖДЕНИЕ - При локальной установке параметр -dest игнорируется
ИНФОРМАЦИЯ - Устанавливаю зависимость: strings
ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - Скачиваю файл: strings-0.4.1.ospx
ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - Устанавливаю пакет strings
ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - Записаны метаданные пакета
ИНФОРМАЦИЯ - Формирую определения модулей пакета (lib.config)
ИНФОРМАЦИЯ - Записаны определения модулей пакета
ИНФОРМАЦИЯ - Добавляем файл: src
ИНФОРМАЦИЯ - Добавляем файл: docs
ИНФОРМАЦИЯ - Добавляем файл: oscript_modules
ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - Создана сборка E:\git\gitsync-plugins\gitsync-plugins-1.4.0.ospx
ИНФОРМАЦИЯ - Сборка пакета завершена
ИНФОРМАЦИЯ - Установка пакета из файла <E:\git\gitsync-plugins\gitsync-plugins-1.4.0.ospx>
**ИНФОРМАЦИЯ - {Модуль E:\git\gitsync-plugins\bin\gitsync\src\cmd\Модули\ПараметрыПриложения.os / Ошибка в строке: 105,0 / Пропущена директива препроцессора #Область}**
{Модуль E:\git\gitsync-plugins\tasks\testing-build.os / Ошибка в строке: 74 / Ошибка установки плагинов из <E:\git\gitsync-plugins\gitsync-plugins-1.4.0.ospx> по причине <>}

После исправления этой ошибки, сборка завершается успешно.

**Comment by khorevaa** [comment]
Вот тут https://github.com/khorevaa/gitsync-plugins/blob/61f963aa575c0aa5faf48595954ff6ec0d0ffa4c/tasks/install-gitsync.os#L89 хардкод думаю надо исправить на текущую версию или просто из мастера брать

**Comment by pravets** [comment]
> Вот тут
> 
> https://github.com/khorevaa/gitsync-plugins/blob/61f963aa575c0aa5faf48595954ff6ec0d0ffa4c/tasks/install-gitsync.os#L89
> 
> хардкод думаю надо исправить на текущую версию или просто из мастера брать

Пробовал master и develop. Тогда новых ошибок прилетает. Позже воспроизведу на master.
Либо может вообще просто ставить актуальный релиз из хаба?

**Comment by pravets** [comment]
Перепроверил. На мастере собирается без ошибок.
