### ISSUE TITLE
Can't assign to global property Console

### ISSUE THREAD

**Issue by 240596448** [oscript-library/gitsync-plugins#62]
КРИТИЧНАЯОШИБКА - {Модуль C:\Users\nadulich.vv\AppData\Local\gitsync\plugins\gitsync-plugins\src\Классы\increment.os / Ошибка в строке: 132 / Внешнее исключение (System.InvalidOperationException): Can't assign to global property Console}

**Comment by khorevaa** [comment]
fix: #63
